### ISSUE TITLE
A Random Doubt

### ISSUE THREAD

**Issue by mrpkdeveloper** [hermanzdosilovic/online-compiler#5]
Hello author,
https://github.com/hermanzdosilovic/online-compiler/blob/master/index.html
in the above file why have you used setTimeout in line number 135. I mean in line 135 you can immediately call the check function when you receive the token ??

It would be helpful if u can leave a comment

**Comment by hermanzdosilovic** [comment]
Hi @mrpkdeveloper,

you are right, you can immediately call the check function.

But, I have decided to wait 2 seconds before the first check since Judge0 would need some time to process this submission, thus if you immediately call the check it is very likely that you will get a submission that is not done yet, and thus you have created unnecessary request to the server.

By waiting 2 seconds, it is more likely that by that time submission is already done and that the next request will in fact give you a submission that has finished.

I hope I have explained this well.

**Comment by mrpkdeveloper** [comment]
@hermanzdosilovic  Thank u for explaining ... that helped me 😀
